 # This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Benchmarks
      run: dotnet run -c Release --project ./Blazique.BenchMarks/Blazique.BenchMarks.csproj --no-build -- --filter * > output.txt
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Benchmark
        tool: 'benchmarkdotnet'
        output-file-path: output.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        benchmark-data-dir-path: 'benchmark-results'
        # Push and deploy GitHub pages branch automatically
        auto-push: true
